### ISSUE TITLE
Show a language (Ja/En) tag to each session

### ISSUE THREAD

**Issue by thagikura** [DroidKaigi/conference-app-2018#193]
## Overview (Required)
- It's helpful to show a language tag (Ja/En) for each session. 
I think showing it on both the list screen and the detailed screen is useful.

**Comment by keima** [comment]
Note: Language category has **3** types: Japanese, English, and Mixed(Contains Japanese and English presentation at same session)

**Comment by konifar** [comment]
@thagikura Thanks for creating the issue!
We had discussed this and decided not to show the language tag in app.
Because all the session's language are synced with the language of its description, we thought it doesn't need to show the language tag on the screen.

As @keima said there is `mixed language` session,  but actually there is only one. so we decided we do not support it on the app.

Let me close this for now. Thanks again!! 👍

**Comment by thagikura** [comment]
Fair enough. Thanks for the clarification!
