### ISSUE TITLE
[Assigned] The layout at empty is displayed for a moment at the transition to the my session screen.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#251]
## Overview (Required)
- Despite I registered several My Sessions, the layout when there is no My Session for a moment is displayed.

**Comment by atsuko-fukui** [comment]
🙋

**Comment by konifar** [comment]
Thanks! Assigned 👍

**Comment by atsuko-fukui** [comment]
As @takahirom - san said the phrase _for a moment_, it seems like network issue because favorite database uses Firestore.

Here is my suggestion:
1. Change visibility of `layout when there is no My Session` (mysessionInactiveGroup) to `gone`
2. Show `ProgressBar` until get favorite sessions (same behavior as session fragment)
3. Set appropriate visibility to mysessionInactiveGroup

What do you think? @takahirom @konifar

**Comment by konifar** [comment]
👀

**Comment by takahirom** [comment]
I think it is perfect 💯

**Comment by atsuko-fukui** [comment]
Thanks, I'll send pull request later 😎
