### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#256]
## Overview (Required)
-

## Links
-

## Screenshot
<img src="" width="300" />

**Comment by atsuko-fukui** [comment]
Can I try this? 

There is no description but my understanding is:

 - convert `left` / `right` to `start` / `end`
     - e.g.) `layout_constraintLeft_toLeftOf` -> `layout_constraintStart_toStartOf`
 - use lint
    - unfortunately, lint does not find `RtlHardcoded` related with ConstraintLayout 😿 
    - just grep for ConstraintLayout

**Comment by KeithYokoma** [comment]
@atsuko-fukui Yes, definitely!

FYI: There might be additional work other than replacing left/right with start/end.

1. Some drawable assets need to be flipped horizontally.
  We can use `android:autoMirrored` for those since `minSdkVersion = 19`, although we need to create XML files for image assets to flip them horizontally.
2. android.support.v4.view.ViewPager does not support RTL direction scrolling.
  There are several alternatives that add RTL support for ViewPager so we need to replace the current ViewPager with one of them if needed. I think it's not mandatory though 😂.

**Comment by atsuko-fukui** [comment]
@KeithYokoma Thank you for you comment.

1. I don't know which icon we should be flipped 🤔 Like characters, symbols should be treated as it sees, I think. Do you mean directional symbol like arrows (->) ?

2. I didn't know that! 😂 I try this with another issue if we need.

**Comment by KeithYokoma** [comment]
@atsuko-fukui Yes, flipping the directional symbols is the most important one! You can find more about flipping drawables here(https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-ui-mirroring-overview)

**Comment by KeithYokoma** [comment]
@atsuko-fukui Quick workaround for ViewPager is to have a ViewPager contents list in a reverse order when it's RTL!
