### ISSUE TITLE
[Assigned] wrong margin in session detail screen on API Level19 emulator

### ISSUE THREAD

**Issue by punchdrunker** [DroidKaigi/conference-app-2018#288]
## Overview (Required)
similar to #287

-  margin or padding for session level label and footer textView is apparently broken on api level 19

## Links
-

<img width="300px" src="https://user-images.githubusercontent.com/135589/35096298-05b27f12-fc8f-11e7-8f4b-2a5054ce6e0b.png" />

**Comment by IsseiAoki** [comment]
Can I try this issue?

**Comment by jmatsu** [comment]
Appreciate 🎉 
Please go ahead!

**Comment by IsseiAoki** [comment]
It seems that the bug is related to `android:lineSpacingMultiplier` attribute. 
If I comment out the corresponding line of the `text_appearance.xml`, it works perfectly.
But I couldn't find the solution that don't comment out the `android:lineSpacingMultiplier` attribute.
Can you give me some advice?
