### ISSUE TITLE
[Assigned] Bottom margin in My Sessions page is too small

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#356]
## Overview (Required)

<img width="581" alt="20180120_185511_screenshot_2018-01-20-18-54-39 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182215-90cd665e-fe13-11e7-9ee1-4ec9eb9f612c.png">

**Comment by yt-tkhs** [comment]
🙋

**Comment by takahirom** [comment]
Thanks 👍 Assigned

**Comment by yt-tkhs** [comment]
I have questions 👀 

1. The other pages (i.e. AllSessions and RoomSessions) have small bottom margin, and is it intentional? If it is not intentional, I will fix it in the same PR. 

2. I've never seen the design file, but The margins between SessionItems in AllSessions and FavoriteSessions are different, is it intentional? (If this will be fixed, 1's fixes are affected with my implementation.)

**Comment by konifar** [comment]
> The other pages (e.g. AllSessions and RoomSessions) have small bottom margin, and is it intentional? If it is not intentional, I will fix it in the same PR.

Not intentional. We would be happy if you'll fix it 🙇 

> I've never seen the design file, but The margins between SessionItems in AllSessions and FavoriteSessions are different, is it intentional? (If this will be fixed, 1's fixes are affected with my implementation.)

Not intentional too. BTW, I want to invite you to Zeplin project. Can you tell me your email here or via DM?

**Comment by yt-tkhs** [comment]
Thanks for your answer, and I will fix that!
Yes, I want to see Zeplin. 🙇 
Email address is this:MASKED

**Comment by konifar** [comment]
Thanks! Invited you. please check your mail box!
