### ISSUE TITLE
I want to be able to go to GitHub and Twitter and etc.. of the speaker in SpeakerDetailFragment .

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#515]
## Overview (Required)
- It is a very abstract request, but this is all.
- We have that datas  https://github.com/DroidKaigi/conference-app-2018/blob/master/model/src/main/java/io/github/droidkaigi/confsched2018/model/Speaker.kt#L8

**Comment by takahirom** [comment]
I think using BottomSheet 🤔 
http://yuki312.blogspot.jp/2017/07/replace-dialog-to-bottomsheet.html

**Comment by takahirom** [comment]
When tap speaker image. I am thinking of showing BottomSheet.
The first time, I think icons are not needed.
Please show texts in the BottomSheet.
Twitter
GitHub
Website
...

**Comment by kiuchikeisuke** [comment]
I also want this function !! 😄 

But I have concerns..🤔

> When tap speaker image,

I think that it is a bit difficult  for users to notice the action, because the speaker image icon is not seem to be able to click... :anguished:

So, I have 2 proposed amendment.

1st : Switch to speaker image icon that we can notich that it is clickable! (Ex. like floating button). And if users click speaker image icon, show BottomSheet.

2nd : Simply, Add Twitter, Github, Blog.. Button like SpeakerDetailFragment's Header Button.And if users click these Button , open each Apps(It same SpeakerDetailFragment's Header Button)

**Comment by takahirom** [comment]
1st: I think it's a bit strange that the image is an action button. AndI think floating action button should be the main action.  🤔 

2nd: Do you say about `AboutThisAppFragent`?

**Comment by takahirom** [comment]
2nd I don't like that 😭  Because the material design says this

> Only one floating action button is recommended per screen
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

**Comment by kiuchikeisuke** [comment]
Sorry for giving a misunderstanding. The example was bad...🙇

>1st: I think it's a bit strange that the image is an action button. And I think floating action button should be the main action.

I think so too.1st idea was simply meaning to put a shadow on the current icon.

> 2nd: Do you say about AboutThisAppFragent?

Yes! AboutThisAppFragment!

**Comment by takahirom** [comment]
I think 1st one is better.
If you do this, please note that it can conflict this implementation.
https://github.com/DroidKaigi/conference-app-2018/issues/64

**Comment by takahirom** [comment]
I think first time shadow is not needed.
But you can please do it👍

**Comment by kiuchikeisuke** [comment]
ok,if this issue is not  assigned to amyone by today's night, I try this !

**Comment by takahirom** [comment]
@kiuchikeisuke Can you do this? 😄

**Comment by kiuchikeisuke** [comment]
ok, I try it !! 😄  (But I might give up.. 😭

**Comment by kiuchikeisuke** [comment]
I have a question 🤔 

Blog and Company Icon don't exist..(Twitter and Github icon exist)
Should I look for free icons?

**Comment by takahirom** [comment]
@kiuchikeisuke 
You can implement only text. But If you want, Please use material icons 🙇 
https://material.io/icons/

**Comment by kiuchikeisuke** [comment]
Okey, I see!!. I will use bussiness icon for company icon , bold icon for blog icon. 😄 

And there is something I want to hear.. 😢 
For bottomsheetDialog, I'd like to make to the icon size 48dp.
Already, twitter, blog, and company icon is done.But github icon is not completed,because that resources are provided only .ai and .eps . https://github.com/logos
 I can't open these extension.. 😭 

So, is it possible to have svg or psd file of github provided?

**Comment by takahirom** [comment]
@kiuchikeisuke I invited to Zeplin. Can you find GitHub icon?

**Comment by kiuchikeisuke** [comment]
Thank you for inviting me!! I got github Icon!! 😄
